// vue-test/src/components/InputText.vue
<template>
    <div>
        <input type="text" :value="text" @input="input">
        <span>输入的文字为：{{text}}</span>
    </div>
</template>
<script>
export default {
    props: ['text'],
    updated() {
        console.log('组件3更新')
    },
    methods: {
        input(e) {
            this.$emit('input', e.target.value)
        }
    }
}
</script>

// react-redux-immutable-test/src/components/InputText.js
import React, { Component } from 'react'

export default class extends Component {
    componentDidUpdate() {
        console.log('组件3更新')
    }
    render() {
        return (
            <div>
                <input value={this.props.text} onInput={(e) => { this.props.onInput(e.target.value) }}/>
                <span>{this.props.text}</span>
            </div>
        )
    }
}
