// vue-test/src/components/List2.vue
<template>
    <div>
        <div>组件2</div>
        <div v-for="item in list" :key='item.name'>
            <span>姓名：{{item.name}},</span>
            <span>年龄：{{item.age}}</span>
        </div>
    </div>
</template>
<script>
export default {
    props: ['list'],
    updated() {
        console.log('组件2更新')
    }
}
</script>

// react-redux-immutable-test/src/components/List2.js
import React, { Component } from 'react'

export default class extends Component {
    componentDidUpdate() {
        console.log('组件2更新')
    }
    render() {
        let list = this.props.list.toJS().map(item => {
            return (
                <div key={item.name}>
                    <span>姓名：{item.name}</span>
                    <span>年纪：{item.age}</span>
                </div> 
            )
        })
        return (
            <div>
                {list}
            </div>
        )
    }
}
